import {random} from './universe.js';
import {cross,sub,dot} from './math.js';
function orient(vertices,faces,centre=[0,0,0]){return faces.map(face=>{const a=vertices[face[0]],b=vertices[face[1]],c=vertices[face[2]];return dot(cross(sub(b,a),sub(c,a)),sub(a,centre))<0?[...face].reverse():face;});}
function merge(parts){const vertices=[],faces=[];for(const part of parts){const offset=vertices.length;vertices.push(...part.vertices);faces.push(...part.faces.map(f=>f.map(i=>i+offset)));}return {vertices,faces};}
function hull(outline,thickness=4,offset=[0,0,0]){const n=outline.length,vertices=[],centreX=outline.reduce((s,v)=>s+v[0],0)/n,centreZ=outline.reduce((s,v)=>s+v[1],0)/n;for(const y of [-thickness/2,thickness/2])for(const [x,z] of outline){const bevel=y>0&&thickness>3?.8:1;vertices.push([centreX+(x-centreX)*bevel+offset[0],y+offset[1],centreZ+(z-centreZ)*bevel+offset[2]]);}const faces=[Array.from({length:n},(_,i)=>i),Array.from({length:n},(_,i)=>i+n)];for(let i=0;i<n;i++)faces.push([i,(i+1)%n,(i+1)%n+n,i+n]);const centre=vertices.reduce((s,v)=>s.map((n,i)=>n+v[i]/vertices.length),[0,0,0]);return {vertices,faces:orient(vertices,faces,centre)};}
function tapered(w,h,front,back,offset=[0,0,0]){const vertices=[[0,0,front],[-w,-h,0],[w,-h,0],[w,h,0],[-w,h,0],[-w*.6,-h*.7,back],[w*.6,-h*.7,back],[w*.6,h*.7,back],[-w*.6,h*.7,back]].map(v=>v.map((x,i)=>x+offset[i]));const faces=[[0,2,1],[0,3,2],[0,4,3],[0,1,4],[1,2,6,5],[2,3,7,6],[3,4,8,7],[4,1,5,8],[5,6,7,8]];return {vertices,faces:orient(vertices,faces,offset)};}
function box(x,y,z,w,h,d){return hull([[-w/2,-d/2],[w/2,-d/2],[w/2,d/2],[-w/2,d/2]],h,[x,y,z]);}
function transform(mesh,angle,offset=[0,0,0]){const c=Math.cos(angle),s=Math.sin(angle);return {vertices:mesh.vertices.map(([x,y,z])=>[x*c-y*s+offset[0],x*s+y*c+offset[1],z+offset[2]]),faces:mesh.faces};}
const names=['Reedskipper','Cinder Finch','Longhand','Copper Kite','Silt Runner','Needleback','Drift Weaver','Mothwing','Quiet Loom','Ternfall','Bramble','Orchard Hauler','Cliffstep','Night Lantern','Flint Arrow','Shellkeeper','Veil Runner','Prism Jack','Stone Plover','Hollow Reed','Wiretail','Canopy Warden','Ember Cart','Glass Mantis','Raincatcher','Dust Caller','Deep Bell','Thorn Carrier','Sable Skiff','Ashfall Crown'];
const roles=['trader','pirate','trader','patrol','miner','pirate'];
export const shipClasses=names.map((name,id)=>({name,id,role:([1,5,7,10,13,14,17,18,23,25,27,29].includes(id)?'pirate':[3,9,12,15,21].includes(id)?'patrol':[4,16,22,28].includes(id)?'miner':'trader'),size:17+id%4*2,speed:23+id%7*4,family:['outrigger','needle','freighter','wing','extractor','fork'][id%6]}));
// Original silhouettes: six structural families, five variants in each.
export function shipMesh(id=0){const family=id%6,v=Math.floor(id/6),w=12+v*2,l=18+v*2,parts=[];
 if(family===0){parts.push(tapered(6,4,l,-12));parts.push(hull([[-w-5,-10],[-w-3,8],[-w,15],[-w+4,-10]],5));parts.push(hull([[w-4,-10],[w,15],[w+3,8],[w+5,-10]],5));parts.push(box(0,0,-5,w*2,2,4));}
 else if(family===1){parts.push(tapered(5+v,4,l+14,-13));parts.push(hull([[-w,-15],[-5,1],[0,-5],[5,1],[w,-15]],2));if(v%2===0)parts.push(box(0,6,-8,3,9,7));}
 else if(family===2){parts.push(hull([[-w,-15],[w,-15],[w,5],[6,14],[-6,14],[-w,5]],9+v));parts.push(tapered(5,3,12,-9,[0,8,-3]));parts.push(box(-w+3,0,-19,7,7,8),box(w-3,0,-19,7,7,8));}
 else if(family===3){parts.push(hull([[-w-12,-11],[-w+1,4],[-3,9],[0,l],[3,9],[w-1,4],[w+12,-11],[0,-4]],3));parts.push(tapered(5,5,13,-11));parts.push(box(-w+1,-2,-9,5,5,12),box(w-1,-2,-9,5,5,12));}
 else if(family===4){parts.push(tapered(w,7,10,-17));parts.push(box(-w-4,0,4,5,5,27),box(w+4,0,1,5,5,21));parts.push(hull([[-6,0],[6,0],[9,7],[-9,7]],5,[0,-8,-8]));}
 else{parts.push(hull([[-w,-17],[-w-4,9],[-w+2,l],[-w+6,-8]],6));parts.push(hull([[w-6,-8],[w-2,l],[w+4,9],[w,-17]],6));parts.push(hull([[-w,-12],[w,-12],[w-4,-2],[-w+4,-2]],8));parts.push(tapered(4,3,11,-8,[0,5,-8]));}
 const cockpit=tapered(3.5,2,7,-6,[0,family===2?10:family===4||family===5?6:4,1]);parts.push(cockpit);const mesh=merge(parts);mesh.cockpitStart=mesh.faces.length-cockpit.faces.length;mesh.secondaryStart=parts[0].faces.length;mesh.engines=[[-5,0,-17],[5,0,-17]];return mesh;}
export function rockMesh(seed=0){const rng=random(seed+37),vertices=[[0,17,0],[0,-15,0]];for(let i=0;i<7;i++){const a=i/7*Math.PI*2;vertices.push([Math.cos(a)*(15+rng()*8),rng()*9-4,Math.sin(a)*(15+rng()*8)]);}const faces=[];for(let i=0;i<7;i++)faces.push([0,i+2,(i+1)%7+2],[1,(i+1)%7+2,i+2]);return {vertices,faces:orient(vertices,faces)};}
function dockingHub(){const vertices=[],faces=[],n=8;for(const z of [-24,24])for(let i=0;i<n;i++){const a=(i+.5)/n*Math.PI*2;vertices.push([Math.cos(a)*47,Math.sin(a)*38,z]);}for(let i=0;i<n;i++){const a=(i+.5)/n*Math.PI*2;vertices.push([Math.cos(a)*23,Math.sin(a)*14,-24]);}for(let i=0;i<n;i++){const j=(i+1)%n;faces.push([i,j,n+j,n+i],[i,2*n+i,2*n+j,j]);}faces.push(Array.from({length:n},(_,i)=>n+i));return {vertices,faces:orient(vertices,faces)};}
export function stationMesh(type=0){const parts=[dockingHub()];if(type===0){for(let i=0;i<3;i++){const a=i*Math.PI*2/3;parts.push(transform(box(65,0,4,62,10,15),a));parts.push(transform(box(92,0,7,19,37,48),a));}}else if(type===1){for(let i=0;i<6;i++){const a=i*Math.PI/3;parts.push(transform(box(67,0,12,48,7,13),a));parts.push(transform(box(87,0,13,12,40,34),a));}}else if(type===2){parts.push(box(-71,0,5,64,13,22),box(-92,0,10,24,80,42),box(68,-15,8,55,11,18),box(81,-15,9,20,34,54),box(0,59,10,13,43,16),box(0,77,10,50,14,36));}else{for(const sign of [-1,1]){parts.push(box(sign*66,0,12,47,11,16));parts.push(transform(box(0,0,0,50,50,34),Math.PI/4,[sign*94,0,12]));}}return {...merge(parts),aperture:true};}
export const cargoMesh=merge([box(0,0,0,8,8,11),box(0,0,0,10,3,12)]);
export function planetMesh(){const vertices=[[0,1,0]],faces=[],rows=7,columns=16;for(let j=1;j<rows;j++){const lat=j/rows*Math.PI;for(let i=0;i<columns;i++){const a=i/columns*Math.PI*2;vertices.push([Math.cos(a)*Math.sin(lat),Math.cos(lat),Math.sin(a)*Math.sin(lat)]);}}vertices.push([0,-1,0]);const last=vertices.length-1;for(let i=0;i<columns;i++){const k=(i+1)%columns;faces.push([0,1+i,1+k]);for(let j=0;j<rows-2;j++){const a=1+j*columns;faces.push([a+i,a+columns+i,a+columns+k,a+k]);}faces.push([last,1+(rows-2)*columns+k,1+(rows-2)*columns+i]);}return {vertices,faces:orient(vertices,faces)};}
