import {distance,economies,governments,regions,commodities,species,routeTo} from './universe.js';
import {equipment,weapons,validSave} from './game.js';
import {length,sub} from './math.js';
import {portrait as monkeyPortrait} from './portraits.js';
import {simulatorPanel,trialResults} from './combat-ui.js';
import {weaponFor} from './weapons.js';
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const credits=n=>n.toLocaleString('en-US',{maximumFractionDigits:1});
const portrait=monkeyPortrait('Capuchin');
export class UI{
 constructor(game){this.g=game;this.chartMode='local';this.mount=0;this.simWeapon='burst';this.simEnemy='skirmisher';this.simCount=1;this.chartPoints=[];this.assist=false;this.sound=false;game.onchange=()=>this.renderPanel();$('navigation').innerHTML=[['dock','1','HARBOUR'],['chart','2','CHART'],['market','3','MARKET'],['equipment','4','OUTFITTER'],['pilot','5','PILOT']].map(([id,key,label])=>`<button data-panel="${id}"><kbd>${key}</kbd>${label}</button>`).join('');$('navigation').onclick=e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const command=b.dataset.command;if(command==='pause'){game.paused=!game.paused;game.keys.clear();}else if(command==='weapon')game.cycleTrialWeapon();else if(command==='target')game.cycleTarget();else if(command==='exit')game.endTrial();else if(b.dataset.panel)this.open(b.dataset.panel);};$('help').onclick=()=>this.open('help');$('mode').onclick=()=>{game.mode=game.mode==='vector'?'solid':'vector';this.update();};$('panel').onclick=e=>this.action(e);$('panel').onchange=e=>{if(e.target.id==='sim-enemy'){this.simEnemy=e.target.value;this.renderPanel();}if(e.target.id==='mount'){this.mount=+e.target.value;this.renderPanel();}if(e.target.id==='import')this.import(e.target.files[0]);};$('panel').onkeydown=e=>{if(e.target.id==='search'&&e.key==='Enter'){e.preventDefault();const q=e.target.value.toLowerCase().trim(),s=game.systems.find(s=>s.name.toLowerCase()===q)||game.systems.find(s=>s.name.toLowerCase().includes(q));if(s){game.selected=s.id;this.renderPanel();}else game.notify('No matching system in this region.');}};this.renderPanel();}
 closePanel(){const g=this.g;if(g.panel==='help'&&this.resumeAfterHelp){g.paused=false;this.resumeAfterHelp=false;}g.panel=g.trial&&g.trial.result!==null?'trialResult':g.docked?'dock':null;g.keys.clear();this.renderPanel();}
 open(panel){if(panel===this.g.panel){this.closePanel();return;}if(this.g.trial&&panel!=='help')return;if((this.g.dead||this.g.panel==='trialResult')&&panel!=='help')return;if(panel==='help'&&this.g.panel!=='help'){this.resumeAfterHelp=!this.g.paused;this.g.paused=true;}this.g.panel=this.g.panel===panel?(this.g.docked?'dock':null):panel;this.g.keys.clear();this.renderPanel();}
 action(e){const b=e.target.closest('button');if(!b||b.disabled)return;const a=b.dataset.action,g=this.g;if(!a)return;if(a==='simulator'){g.panel='simulator';this.renderPanel();}if(a==='simWeapon'){this.simWeapon=b.dataset.id;this.renderPanel();}if(a==='simCount'){this.simCount=+b.dataset.count;this.renderPanel();}if(a==='startTrial')g.startTrial(this.simWeapon,this.simEnemy,this.simCount);if(a==='retryTrial')g.startTrial(g.trial.weapon,g.trial.enemy,g.trial.count);if(a==='exitTrial')g.endTrial();if(a==='configureTrial'){this.simWeapon=g.trial.weapon;this.simEnemy=g.trial.enemy;this.simCount=g.trial.count;g.endTrial();g.panel='simulator';this.renderPanel();}if(a==='launch')g.launch();if(a==='fuel')g.refuel();if(a==='trade')g.trade(+b.dataset.index,+b.dataset.amount);if(a==='buy')g.buy(b.dataset.id);if(a==='weapon')g.buyWeapon(b.dataset.id,this.mount);if(a==='missile')g.buyMissile();if(a==='chart'){this.chartMode=this.chartMode==='local'?'regional':'local';this.renderPanel();}if(a==='select'){g.selected=+b.dataset.id;this.renderPanel();}if(a==='assist'){this.assist=!this.assist;this.renderPanel();}if(a==='close')this.closePanel();if(a==='jump'){g.panel=null;g.startJump();this.renderPanel();}if(a==='restore')g.restore();if(a==='export'){g.save();const blob=new Blob([JSON.stringify(g.p,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='SpaceMonkey-station.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}if(a==='identity'){const name=$('pilot-name').value.trim();if(name&&name.length<=30){g.p.name=name;g.p.species=$('pilot-species').value;g.save();g.notify('Pilot registry updated.');}}}
 async import(file){if(!file||!this.g.docked)return;try{const save=JSON.parse(await file.text());if(!validSave(save))throw Error();this.g.storage?.setItem('spacemonkey.station.v1',JSON.stringify(save));this.g.restore();}catch{this.g.notify('That file is not a valid SpaceMonkey station record.');}}
 renderPanel(){const g=this.g,p=g.p,s=g.system;document.body.dataset.panel=g.panel||'flight';document.body.dataset.phase=g.docked?'harbour':'flight';document.body.dataset.trial=String(!!g.trial);document.querySelectorAll('[data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===g.panel));if(!g.panel){$('panel').innerHTML='';return;}let html='',narrow=false;const close=g.docked?'':'<button class="small" data-action="close">ESC · FLIGHT</button>';
 if(g.panel==='dock'){narrow=true;if(!g.docked){html=`<div class="eyebrow">STATION BEACON</div><h1>${esc(s.name)} Harbour</h1><p>Approach the rotating amber aperture. Align with its axis, match its roll and enter at 28 velocity or less.</p><div class="stats"><div><small>DISTANCE</small><strong>${Math.round(length(sub(g.station.pos,g.position)))}</strong></div><div><small>COMPUTER</small><strong>${g.has('autodock')?'FITTED':'—'}</strong></div></div><p>The scanner compass points toward the station. Amber is the harbour beacon; red contacts are hostile.</p><div class="actions">${close}</div>`;}else html=`<div class="row" style="margin-bottom:14px"><div class="eyebrow" style="margin:0">ORBITAL HARBOUR / BERTH 07</div><div class="harbour-launch"><button class="primary small" data-action="simulator">COMBAT SIM ↗</button><button class="small" data-action="launch">LAUNCH ↗</button></div></div><h1>${esc(s.name)} Harbour</h1><div class="station-meta">${economies[s.economy].toUpperCase()} <span>SEC ${s.security}/8</span> <span>TECH ${String(s.tech).padStart(2,'0')}</span></div><p class="harbour-description">${esc(s.description)}</p><div class="stats"><div><small>AVAILABLE CREDIT</small><strong>${credits(p.credits)} <small style="display:inline">CR</small></strong></div><div><small>CARGO HOLD</small><strong>${g.cargoUsed}<span class="muted"> / ${g.capacity}</span></strong></div><div><small>JUMP FUEL</small><strong>${p.fuel.toFixed(1)}<span class="muted"> LY</span></strong></div></div><div class="contact">${portrait}<div><strong>TIKO MARR / CAPUCHIN / HARBOUR ENGINEER</strong><p>“The simulator is live. Pick an emitter, pick an opponent, and show me your flying.”</p></div></div><div class="actions"><button data-action="fuel" ${p.fuel>=6.999?'disabled':''}>REFUEL · ${credits(Math.ceil((7-p.fuel)*4))} CR</button></div><p style="font-size:9px;margin-top:14px">STATION RECORD ${g.saveWarning?'UNAVAILABLE — EXPORT IN PILOT':'SAVED LOCALLY'} · SHIP REPAIRS INCLUDED</p>`;}
 if(g.panel==='market'){html=`<div class="terminal-title"><h2>Commodity exchange</h2><span>${credits(p.credits)} CR · HOLD ${g.cargoUsed}/${g.capacity}</span>${close}</div>`;if(!g.docked)html+='<p>Market access requires docking. Cargo manifest remains available below.</p>';html+=`<table><thead><tr><th>COMMODITY</th><th>CR / UNIT</th><th>STOCK</th><th>HOLD</th><th>TRADE</th></tr></thead><tbody>${commodities.map((c,i)=>`<tr><td>${c.name}${c.illegal?' <span class="warning">†</span>':''}</td><td>${g.market[i].price}</td><td>${g.market[i].stock}</td><td>${p.cargo[i]||'—'}</td><td><button class="small" aria-label="Sell ${c.name}" data-action="trade" data-index="${i}" data-amount="-1" ${!g.docked||!p.cargo[i]?'disabled':''}>−</button><button class="small" aria-label="Buy ${c.name}" data-action="trade" data-index="${i}" data-amount="1" ${!g.docked||g.cargoUsed>=g.capacity||g.market[i].stock<1||p.credits<g.market[i].price?'disabled':''}>+</button></td></tr>`).join('')}</tbody></table><p style="font-size:9px">† Prohibited in security 6–8. Each unit occupies one cargo space. Prices follow local production.</p>`;}
 if(g.panel==='chart'){const target=g.systems[g.selected],d=distance(s,target),reachable=d>0&&d<=Math.min(7,p.fuel)+.00001;html=`<div class="terminal-title"><h2>${this.chartMode==='local'?'Local':'Regional'} chart</h2><div><button class="small" data-action="chart">${this.chartMode==='local'?'REGIONAL':'LOCAL'} [TAB]</button> ${close}</div></div><div class="chart-layout"><canvas id="chart" width="640" height="430" aria-label="Star chart. Click a system to select it; arrow keys move selection."></canvas><div class="system-info"><input id="search" placeholder="Find system · Enter" aria-label="Search systems"><h2>${esc(target.name)}</h2><div class="eyebrow">${regions[p.region]}</div><dl><dt>Distance</dt><dd>${d.toFixed(1)} LY</dd><dt>Economy</dt><dd>${economies[target.economy]}</dd><dt>Government</dt><dd>${governments[target.government]}</dd><dt>Security</dt><dd>${target.security} / 8</dd><dt>Technology</dt><dd>${target.tech} / 12</dd><dt>Population</dt><dd>${target.population} bn</dd><dt>Productivity</dt><dd>${target.productivity} Mcr</dd></dl><p>${esc(target.description)}</p><span class="${reachable?'accent':'muted'}">${d===0?'CURRENT SYSTEM':reachable?'WITHIN FUEL RANGE':'BEYOND FUEL RANGE'}</span>${g.docked?'<p>Destination selected. Launch, clear the station, then press H to jump.</p>':`<div class="actions"><button class="primary" data-action="jump" ${reachable?'':'disabled'}>INITIATE JUMP [H]</button></div>`}<p style="font-size:9px">Ring: available fuel · Cross: current system<br>Arrow keys: select · Enter: jump in flight</p>${g.has('nav')?`<button class="small" data-action="assist">${this.assist?'HIDE':'SUGGEST'} ROUTE</button>${this.assist?`<p>${routeTo(g.systems,p.system,g.selected).map(id=>esc(g.systems[id].name)).join(' → ')}<br>Refuel at each stop.</p>`:''}`:''}</div></div>`;}
 if(g.panel==='equipment'){html=`<div class="terminal-title"><h2>Harbour outfitter</h2><span>${credits(p.credits)} CR · TECH ${s.tech}</span>${close}</div>${!g.docked?'<p>Dock to install equipment.</p>':''}<div class="equipment">${equipment.map(e=>`<article><div><strong>${e.name}</strong><p>${e.description}</p></div><button data-action="buy" data-id="${e.id}" ${!g.docked||g.has(e.id)||p.credits<e.cost||s.tech<e.tech?'disabled':''}>${g.has(e.id)?'INSTALLED':s.tech<e.tech?'TECH '+e.tech:e.cost+' CR'}</button></article>`).join('')}<article><div><strong>Guided missile</strong><p>${p.missiles} / 4 pylons occupied</p></div><button data-action="missile" ${!g.docked||p.missiles>=4||p.credits<45?'disabled':''}>45 CR</button></article></div><hr class="rule"><div class="row"><h2>Emitter installation</h2><select id="mount" style="width:170px" aria-label="Weapon mount">${['Forward','Rear','Port','Starboard'].map((v,i)=>`<option value="${i}" ${i===this.mount?'selected':''}>${v} mount</option>`).join('')}</select></div><div class="equipment">${weapons.map(w=>`<article><div><strong>${w.name}</strong><p>${w.description}</p></div><button data-action="weapon" data-id="${w.id}" ${!g.docked||p.weapons[this.mount]===w.id||p.credits<(w.cost||90)||s.tech<w.tech?'disabled':''}>${p.weapons[this.mount]===w.id?'INSTALLED':s.tech<w.tech?'TECH '+w.tech:(w.cost||90)+' CR'}</button></article>`).join('')}</div>`;}
 if(g.panel==='pilot'){html=`<div class="terminal-title"><h2>Commander registry</h2>${close}</div><div class="contact">${portrait}<div><strong>CMDR ${esc(p.name.toUpperCase())} / ${esc(p.species.toUpperCase())}</strong><p>${g.rating} · ${p.kills} confirmed victories · ${p.legal>3?'WANTED / '+p.legal:'CLEAR RECORD'}</p></div></div><div class="stats"><div><small>CREDIT</small><strong>${credits(p.credits)}</strong></div><div><small>PORT CALLS</small><strong>${p.visits}</strong></div><div><small>REGION</small><strong>${p.region+1} / 8</strong></div></div>${g.docked?`<div class="row"><input id="pilot-name" maxlength="30" value="${esc(p.name)}" aria-label="Commander name"><select id="pilot-species" aria-label="Monkey species">${species.map(x=>`<option ${x===p.species?'selected':''}>${x}</option>`).join('')}</select><button data-action="identity">REGISTER</button></div><div class="actions"><button data-action="export">EXPORT STATION RECORD</button><label style="font-size:9px">IMPORT RECORD<input type="file" id="import" accept="application/json,.json"></label></div>`:'<p>Dock to change your registry or export a station record.</p>'}${g.saveWarning?`<p class="warning">${esc(g.saveWarning)}</p>`:''}<hr class="rule"><div class="eyebrow">RECENT TRANSMISSIONS</div><div class="log">${g.log.map(x=>`<div>› ${esc(x)}</div>`).join('')}</div>`;}
 if(g.panel==='help'){html=`<div class="terminal-title"><h2>Flight manual</h2><button class="small" data-action="close">CLOSE [ESC]</button></div><p class="touch-manual">TOUCH FLIGHT: drag the flight stick to pitch and roll. Hold + / − to change speed and FIRE to shoot; you can use several fingers together. Tap the view button to cycle views. MORE opens equipment controls. Use RESUME after switching apps.</p><div class="manual"><div><div class="eyebrow">CLASSIC FLIGHT</div><dl><dt>↑ ↓ / W S</dt><dd>Pitch up / down</dd><dt>← → / A D</dt><dd>Roll left / right</dd><dt>R / F</dt><dd>Increase / decrease velocity</dd><dt>Space</dt><dd>Fire current emitter; hold and release to use a charge lance</dd><dt>T / N / I</dt><dd>Cycle contact / harbour compass / hail contact</dd><dt>Q (simulator)</dt><dd>Change weapon during a trial</dd><dt>V</dt><dd>Vector / solid vector</dd><dt>7 8 9 0</dt><dd>Forward / rear / port / starboard</dd><dt>J</dt><dd>Space compression, when clear</dd><dt>H</dt><dd>Jump to selected system</dd><dt>M</dt><dd>Arm missile; press again after lock</dd><dt>E</dt><dd>Activate fitted countermeasures</dd><dt>C</dt><dd>Toggle fitted docking computer</dd><dt>X / G</dt><dd>Dump cargo / fitted region drive</dd><dt>P / Esc</dt><dd>Pause / close console</dd><dt>1–5 / L</dt><dd>Consoles / launch from harbour</dd></dl></div><div><div class="eyebrow">WINNING A FIGHT</div><p>Roll until your opponent is above the sight, then pitch up to bring it into the centre. Ease the throttle on a close pass. The small amber chevron points toward an off-screen contact.</p><p>Needles sweep past; interceptors jink; gunships carry armour; aces hit hard; missile boats launch guided weapons. Keep ECM ready. Damaged hulls trail fragments. Shields need three seconds clear of hits before recharging.</p><div class="eyebrow">YOUR FIRST JOURNEY</div><p>Buy a little locally produced cargo. Choose a reachable system in Chart. Launch and fly clear of the station, then press H.</p><p>After arrival, the amber compass in your scanner points toward the station. R increases speed. J compresses safe space; nearby contacts interrupt it.</p><div class="eyebrow">MANUAL DOCKING</div><p>Approach the station’s front face. Align with the amber aperture and match its rotation. Enter near the centre at 28 velocity or less. Collisions hurt.</p><div class="eyebrow">A QUIET, DANGEROUS UNIVERSE</div><p>Blue scanner contacts are patrols, red are hostile, green are traffic. Fields recharge from reactor energy. Let emitters cool. Scoop cargo just below your nose with a collection cradle.</p><p>Progress saves at stations, including purchases. Destruction restores that record unless a return capsule is fitted. Sound is optional. Flight pauses when this browser tab is hidden.</p></div></div>`;}
 if(g.panel==='simulator')html=simulatorPanel(this.simWeapon,this.simEnemy,this.simCount);if(g.panel==='trialResult'&&g.trial){html=trialResults(g);}if(g.panel==='death'){narrow=true;html='<div class="eyebrow warning">FLIGHT RECORD TERMINATED</div><h1>Out beyond the harbour.</h1><p>Your ship was destroyed. The most recent station record remains intact.</p><button class="primary" data-action="restore">RESTORE STATION RECORD</button>';}
 $('panel').innerHTML=`<section class="terminal ${narrow?'narrow':''}">${html}</section>`;if(g.panel==='chart')this.drawChart();this.update();}
 drawChart(){const canvas=$('chart');if(!canvas)return;const ctx=canvas.getContext('2d'),g=this.g,s=g.system,w=640,h=430,local=this.chartMode==='local',scale=local?21:5.7,center=local?[s.x,s.y]:[31.5,31.5];const xy=s=>[w/2+(s.x-center[0])*scale,h/2+(s.y-center[1])*scale];ctx.fillStyle='#060d11';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#12252d';ctx.lineWidth=1;for(let x=0;x<w;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}for(let y=0;y<h;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}const current=xy(s);ctx.beginPath();ctx.arc(...current,g.p.fuel*scale,0,Math.PI*2);ctx.fillStyle='#15373220';ctx.fill();ctx.strokeStyle='#3f7667';ctx.setLineDash([4,5]);ctx.stroke();ctx.setLineDash([]);this.chartPoints=[];for(const star of g.systems){const p=xy(star);if(p[0]<5||p[0]>w-5||p[1]<5||p[1]>h-5)continue;this.chartPoints.push({id:star.id,x:p[0],y:p[1]});ctx.fillStyle=distance(star,s)<=g.p.fuel?'#b6d2bc':'#5a747b';ctx.fillRect(p[0]-1.5,p[1]-1.5,3,3);if(local){ctx.font='10px Consolas,monospace';ctx.fillStyle='#728b91';ctx.fillText(star.name,p[0]+7,p[1]-5);}}ctx.strokeStyle='#edb86b';ctx.beginPath();ctx.moveTo(current[0]-7,current[1]);ctx.lineTo(current[0]+7,current[1]);ctx.moveTo(current[0],current[1]-7);ctx.lineTo(current[0],current[1]+7);ctx.stroke();const target=xy(g.systems[g.selected]);ctx.strokeRect(target[0]-7,target[1]-7,14,14);if(this.assist&&g.has('nav')){const route=routeTo(g.systems,g.p.system,g.selected);ctx.beginPath();route.forEach((id,i)=>i?ctx.lineTo(...xy(g.systems[id])):ctx.moveTo(...xy(g.systems[id])));ctx.strokeStyle='#edb86b70';ctx.stroke();}ctx.fillStyle='#648089';ctx.font='10px Consolas,monospace';ctx.fillText(`${regions[g.p.region].toUpperCase()} / 256 SYSTEMS`,15,20);canvas.onclick=e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*w,y=(e.clientY-r.top)/r.height*h;const point=this.chartPoints.slice().sort((a,b)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(b.x-x,b.y-y))[0];if(point){g.selected=point.id;this.renderPanel();}};}
 chartKey(code){const g=this.g,origin=g.systems[g.selected],dir={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[code];if(!dir)return;const candidates=g.systems.filter(s=>(s.x-origin.x)*dir[0]+(s.y-origin.y)*dir[1]>.1);candidates.sort((a,b)=>{const score=s=>{const x=s.x-origin.x,y=s.y-origin.y;return Math.hypot(x,y)+Math.abs(x*dir[1]-y*dir[0])*2;};return score(a)-score(b);});if(candidates[0]){g.selected=candidates[0].id;this.renderPanel();}}
 updateNavigation(){
  const g=this.g,state=String(!!g.trial)+'/'+g.paused+'/'+(g.panel==='trialResult');if(this.navState===state)return;this.navState=state;
  if(g.trial){const finished=g.trial.result!==null;$('navigation').innerHTML='<button data-command="pause" '+(finished?'disabled':'')+'>'+(g.paused?'RESUME':'PAUSE')+'</button><button data-command="weapon" '+(finished?'disabled':'')+'>Q · WEAPON</button><button data-command="target" '+(finished?'disabled':'')+'>T · TARGET</button><button data-panel="help">MANUAL</button><button data-command="exit">EXIT SIM</button>';}
  else $('navigation').innerHTML=[['dock','1','HARBOUR'],['chart','2','CHART'],['market','3','MARKET'],['equipment','4','OUTFITTER'],['pilot','5','PILOT']].map(([id,key,label])=>'<button data-panel="'+id+'"><kbd>'+key+'</kbd>'+label+'</button>').join('');
  document.querySelectorAll('[data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===g.panel));
 }
 updateCombatReadout(){
  const g=this.g,w=weaponFor(g),target=g.target,aim=g.aimTarget,mobile=window.matchMedia('(pointer:coarse),(max-width:900px)').matches;
  const name=$('weapon-name'),state=$('weapon-state'),contact=$('contact-name'),detail=$('contact-detail');if(!name)return;
  name.textContent=w?w.name.toUpperCase():'NO EMITTER FITTED';
  state.textContent=g.docked?'FORWARD MOUNT':g.projectiles.some(m=>m.hostile)?'MISSILE INBOUND / ECM':g.overheated?'OVERHEATED / COOLING':g.charging?'CHARGE '+Math.round(g.weaponCharge*100)+'% / RELEASE TO FIRE':g.trial?(mobile?'FIRE / SHOOT · WEAPON / SWITCH':'Q / WEAPON · SPACE / FIRE'):w?.charge?'HOLD / RELEASE TO FIRE':w?.id==='beam'?'CONTINUOUS DISCHARGE':'EMITTER READY';
  state.classList.toggle('warning',g.overheated||g.projectiles.some(m=>m.hostile));
  contact.textContent=target?target.name.toUpperCase():g.docked?'REEDSKIPPER / BERTH 07':'HARBOUR BEACON';
  detail.textContent=target?Math.round(length(sub(target.pos,g.position)))+' U · '+(target.hp/target.maxHp<.3?'CRITICAL':target.hp/target.maxHp<.65?'DAMAGED':target.armour?'ARMOURED':'HULL INTACT')+(w&&length(sub(target.pos,g.position))>w.range?' · OUT OF RANGE':aim?.id===target.id?' · IN SIGHT':'')+(mobile?'':' · '+target.pilot+' / '+target.species):g.docked?g.cargoUsed+'/'+g.capacity+' CARGO · '+credits(g.p.credits)+' CR':Math.round(g.stationRange)+' U · '+g.hostileCount+' HOSTILE';
  $('combat-readout').classList.toggle('tracking-hostile',target?.state==='attack');
 }

 update(){const g=this.g;this.updateCombatReadout();this.updateNavigation();$('location').textContent=g.system.name.toUpperCase();$('status').textContent=g.docked?'DOCKED':g.paused?'PAUSED':g.trial?'COMBAT SIM':g.cruise?'COMPRESSION':'IN FLIGHT';$('mode').textContent='V · '+(g.mode==='vector'?'VECTOR':'SOLID VECTOR');$('viewlabel').textContent=['FORWARD / 01','REAR / 02','PORT / 03','STARBOARD / 04'][g.view];$('flight-message').textContent=g.messageTime>0&&!g.panel&&!(g.radio&&g.radio.until>g.time)?g.message:'';$('flight-context').textContent=g.docked?'BERTH 07 · ROTATING HABITAT':g.trial?'COMBAT SIMULATOR / RECORD PROTECTED':g.interstitial?'HOLLOW-SPACE / NO STABLE BEACON':g.autodock?'HARBOUR COMPUTER / APPROACH':g.cruise?'SPACE COMPRESSION / ACTIVE':`STATION ${Math.round(length(sub(g.station.pos,g.position)))} U`;$('target-readout').textContent=g.docked?'VESSEL / REEDSKIPPER':g.armed?(g.lockTime>=1?'MISSILE LOCK / M TO FIRE':'MISSILE ARMED / ACQUIRING'):g.trial?`${g.trial.kills} / ${g.trial.count} CONTACTS DOWN`:`DEST ${g.systems[g.selected].name.toUpperCase()}`;$('pilot-footer').textContent=`CMDR ${g.p.name.toUpperCase()} / ${g.p.species.toUpperCase()}`;$('footer-hint').textContent=g.docked?'THE NEXT JOURNEY IS YOURS.':'ARROWS FLY · R/F SPEED · SPACE FIRE · T TARGET · P PAUSE';$('contacts').textContent=`${g.entities.length} CONTACTS`;const gauge=(label,value,max,unit='',color='')=>`<div class="gauge"><label>${label}</label><div class="bar ${color}"><b style="width:${Math.max(0,value/max*100)}%"></b></div><span class="number">${unit==='LY'?value.toFixed(1):Math.round(value)}${unit}</span></div>`;$('gauges-left').innerHTML=gauge('VELOCITY',g.speed,100)+gauge('FWD FLD',g.front,g.maxShield)+gauge('AFT FLD',g.rear,g.maxShield)+gauge('REACTOR',g.energy,100,'',g.energy<25?'red':'');$('gauges-right').innerHTML=gauge('WPN HEAT',g.heat,100,'',g.overheated?'red':'amber')+gauge('CABIN',g.cabin,100,'',g.cabin>80?'red':'')+gauge('FUEL',g.p.fuel,7,'LY','amber');$('nav').textContent=g.has('ecm')?(g.damageEquipment==='ecm'?'ECM FAULT':g.energy<15?'ECM LOW POWER':'ECM READY'):'ECM —';$('missiles').textContent='MSL '+('◆'.repeat(g.p.missiles)||'—');}
}



