export function random(seed){let s=seed>>>0;return ()=>{s=(Math.imul(s,1664525)+1013904223)>>>0;return s/4294967296;};}
export const economies=['Cultivation','Extraction','Industry','Fabrication','Commerce','Frontier'];
export const governments=['Cooperative','Council','Free port','Protectorate','Assembly','Syndicate'];
export const species=['Capuchin','Macaque','Tamarin','Mandrill','Marmoset','Langur','Spider monkey','Howler monkey'];
export const regions=['The Copper Reach','Veilward Expanse','The Quiet Arc','Cinder Territories','The Long Orchard','Sable Meridian','The Glassward Rim','Outer Canopy'];
const starts=['Or','Nem','Va','Kes','Ti','Sul','Ae','Mor','Il','Fen','Ush','Dar','Pel','Zin','Cor','Nal'];
const mids=['a','e','i','o','u','ae','io','ei'];
const ends=['va','rin','th','lo','vek','na','mar','sen','di','qua','tor','la','vis','do','chel','mu'];
export const commodities=[
 {name:'Seed grain',base:9,source:0},{name:'Woven fibres',base:15,source:0},{name:'Medicinal cultures',base:42,source:3},{name:'Reactor salts',base:31,source:1},{name:'Fermented nectar',base:23,source:0},{name:'Artisan keepsakes',base:78,source:4},{name:'Logic wafers',base:88,source:3},{name:'Servo assemblies',base:62,source:2},{name:'Hull ceramics',base:39,source:2},{name:'Emitter cores',base:105,source:3,illegal:true},{name:'Crystal ore',base:57,source:1},{name:'Catalyst metals',base:135,source:1},{name:'Prism stones',base:180,source:1},{name:'Polymer resin',base:28,source:2}
];
export function generateRegion(region=0){const rng=random(0x53ac917d+region*91397);return Array.from({length:256},(_,id)=>{const a=Math.floor(rng()*16),b=Math.floor(rng()*8),c=Math.floor(rng()*16);const economy=Math.floor(rng()*6),security=1+Math.floor(rng()*8),tech=1+Math.floor(rng()*12),prosperity=rng();return {id,region,name:starts[a]+mids[b]+ends[c]+(id%23===0?' Prime':''),x:2+(id%16)*3.7+rng()*2.2,y:2+Math.floor(id/16)*3.7+rng()*2.2,economy,security,tech,prosperity,government:Math.floor(rng()*6),population:Math.round((1+rng()*8)*100)/100,productivity:Math.round(200+prosperity*tech*850),hue:Math.floor(25+rng()*170),stationType:Math.floor(rng()*4),seed:Math.floor(rng()*0xffffffff),description:`${['A patient outpost','A scattered colony','An old trading haven','A secluded settlement'][Math.floor(rng()*4)]} known for ${['ceramic observatories','hanging orchards','night markets','wind-carved plateaus','quiet radio choirs','glass-roofed workshops'][Math.floor(rng()*6)]}. ${['Independent monkey crews keep its docks busy.','Its monkey councils value reliable visitors.','Travelling monkey clans gather here between journeys.'][Math.floor(rng()*3)]}`};});}
export function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y);}
export function marketFor(system,epoch=0){const rng=random(system.seed+epoch*131);return commodities.map(c=>{let factor=c.source===system.economy?.56:1.05+(system.economy===4?.12:0);factor*=.86+system.prosperity*.24+rng()*.23;return {price:Math.max(1,Math.round(c.base*factor)),stock:Math.floor((c.source===system.economy?30:6)+rng()*28)};});}
export function routeTo(systems,from,to,range=7){const queue=[from],prev=new Map([[from,null]]);for(let i=0;i<queue.length;i++){const id=queue[i];if(id===to){const route=[];for(let n=to;n!==null;n=prev.get(n))route.unshift(n);return route;}for(const s of systems)if(!prev.has(s.id)&&distance(systems[id],s)<=range){prev.set(s.id,id);queue.push(s.id);}}return [];}
export function rank(kills){return ['Unproven','Steady hand','Pathfinder','Pursuer','Vanguard','Nightwatch','Starwarden','Beyond legend'][[0,5,20,60,160,450,1200,4000].filter(n=>kills>=n).length-1];}
